version: '3'

services:
  app:
    build: 
      context: ./project
    ports: 
      - 3000:3000
    volumes: 
      - ./project:/home/jerry/code/docker-app:cached

  db: 
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined
